baseurl = "https://trustworthy.messaging.lu"
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-highlights"
title = "Position Paper on Trustworthy Messaging"
[params]
backgroundpersection = true
description = "Your Description"
email = "your@mail.com"
name = "Your Name"
[params.footer]
enable = true
[[params.footer.copyright.notice]]
text = "© Untitled"
[[params.footer.copyright.notice]]
text = "Design: [HTML5UP](//html5up.net)"
[[params.footer.copyright.notice]]
text = "Demo Images: [Unsplash](//unsplash.com/)"
[params.footer.social_list]
enable = true
[[params.footer.social]]
icon = "fa-twitter"
link = "#"
title = "Twitter"
[[params.footer.social]]
icon = "fa-facebook"
link = "#"
title = "Facebook"
[[params.footer.social]]
icon = "fa-instagram"
link = "#"
title = "Instagramm"
[[params.footer.social]]
icon = "fa-dribbble"
link = "#"
title = "Dribbble"
[[params.footer.social]]
icon = "fa-envelope"
link = "#"
title = "Email"
[params.hero]
buttontext = "begin"
description = "a fun litte { responsive } single Pager by [HTML5UP](//html5up.net)"
title = "Highlights"
type = "hero"
[[params.block]]
buttontext = "next"
description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
id = "about"
picture = "pic01.jpg"
title = "Who am I"
type = "text"
[[params.block]]
buttontext = "next"
description = "Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet vulputate."
id = "skills"
picture = "pic02.jpg"
title = "Stuff I do"
type = "list"
[[params.block.item]]
icon = "fa-camera-retro"
icontype = "fas"
title = "Magna Etiam"
[[params.block.item]]
icon = "fa-pencil-alt"
icontype = "fas"
title = "Lorem Ipsum"
[[params.block.item]]
icon = "fa-code"
icontype = "fas"
title = "Nulla Tempus"
[[params.block.item]]
icon = "fa-coffee"
icontype = "fas"
title = "Sed Feugiat"
[[params.block]]
buttontext = ""
description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
id = "infos"
picture = "pic03.jpg"
title = "One more thing"
type = "text"
[[params.block]]
buttontext = ""
description = ""
id = "contact"
picture = "pic05.jpg"
title = "Get in Touch"
type = "contact"
[params.block.form]
buttontext = "send message"
email = "Your Email"
message = "Your Message"
name = "Name"
